AbArticulus/home/urls.py
from django.conf.urls import patterns, url

from home.views import HomeView


urlpatterns = patterns(
    '',
    url(r'^$', HomeView.as_view(), name='home_page'),
)

AbArticulus/mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'', include('home.urls', namespace="home")),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^ngtodo/', include('todo.urls', namespace="ngtodo")),
    url(r'^auth/', include('authentication.urls', namespace="authentication")),
    url(r'^timetable/', include('time_table.urls', namespace="time_table")),
    url(r'^api/', include('api.urls', namespace="api")),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rosi_parse/', include('rosi_parse.urls', namespace='rosi')),
)

AbArticulus/todo/urls.py
from django.conf.urls import patterns, url

from todo.views import TodoView, TodoList, TodoDetail


urlpatterns = patterns(
    '',
    url(r'^$', TodoView.as_view(), name='todo_home'),
    url(r'^todos/$', TodoList.as_view(), name="todos_list"),
    url(r'^todos/(?P<pk>[0-9]+)/$', TodoDetail.as_view(), name="todos_update"),
)

AbArticulus/home/models.py
from django.db import models


class TestModel(models.Model):
    first_name = models.CharField(max_length=30)


class Todo(models.Model):
    item = models.CharField(max_length=255)
    is_done = models.BooleanField(default=False)

AbArticulus/home/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        return {"current_page_name": "Home"}

AbArticulus/home/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>AbArticulus Home Page</title>
    <link href="{% static "AbArticulusHomeApp/css/AbArticulusHomeApp.dist.css" %}" rel="stylesheet">
    <script src="{% static "AbArticulusHomeApp/js/AbArticulusHomeApp.dist.js" %}"></script>
</head>

<body>

    <div class="brand">AbArticulus</div>
    <div class="tagline">What cannot be avoided must be endured</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Mobile Nav -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url "home:home_page" %}">AbArticulus</a>
            </div>
            <!-- Bigger Nav-->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url "social:begin" "google-oauth2" %}">Sign In</a>
                    </li>
                    <li>
                        <a href="{% url "ngtodo:todo_home" %}">Todo List</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12 text-center">
                    <div id="carousel-example-generic" class="carousel slide">
                        <!-- Indicators -->
                        <ol class="carousel-indicators hidden-xs">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            <div class="item active">
                                <img class="img-responsive img-full" src="{% static "img/slide-1.png" %}" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="{% static "img/slide-2.png" %}" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="{% static "img/slide-3.png" %}" alt="">
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="icon-next"></span>
                        </a>
                    </div>
                    <h2 class="brand-before">
                        <small>Welcome to</small>
                    </h2>
                    <h1 class="brand-name">AbArticulus</h1>
                    <hr class="tagline-divider">
                    <h2>
                        <small>By
                            <strong>Team Insomnia</strong>
                        </small>
                    </h2>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Build a Schedule
                        <strong>worth following</strong>
                    </h2>
                    <hr>
                    <img class="img-responsive img-border img-left img-small" src="{% static "img/intro-pic.jpg" %}" alt="">
                    <hr class="visible-xs">
                    <p>If you want to get organized and on top of your classes than you have come to the right place. AbArticulus helps you discover and report due dates, class and social events happening in or around campus.</p>
                    <p>If you've ever missed a test, a deadline or simply misprioritized your work than we can help. Using sophisticated measurements and algorithms, we'll suggest a study schedule for you and help you build it.</p>
                    <p>Best of all, it's completely built on Google Calendar and so you'll be able to view and edit events from your phone as well as share your calendar with others. Get started today!</p>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; AbArticulus.me 2014</p>
                </div>
            </div>
        </div>
    </footer>


    {% if backend %}
      <div id="email-required-modal" class="modal fade">
        <form action="{% url "social:complete" backend=backend %}" method="post" role="form">{% csrf_token %}
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Email required</h4>
              </div>

              <div class="modal-body">
                <p>A valid email address is required. It must end in mail.utoronto.ca</p>
                <div class="form-group">
                  <label class="control-label" for="email">Email address:</label>
                  <input class="form-control" id="email" type="email" name="uoft_email" value="" />
                </div>
              </div>

              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Continue</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    {% endif %}

    <div id="validation-sent-modal" class="modal fade">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Email Validation Sent</h4>
          </div>

          <div class="modal-body">
            <p>An email validation was sent{% if email %} to <code>{{ email }}</code>{% endif %}.</p>
            <p>Click the link sent to finish the authentication process.</p>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>


    <!-- Script to Activate the Carousel -->
    <script>
        window.showEmailValidation = {% if email_required %} true {% else %} false {% endif %};
        window.emailVerificationSent = {% if validation_sent %} true {% else %} false {% endif %};
    </script>

</body>

</html>