AbArticulus/home/urls.py
from django.conf.urls import patterns, url

from home.views import HomeView


urlpatterns = patterns(
    '',
    url(r'^$', HomeView.as_view(), name='home_page'),
)

AbArticulus/mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'', include('home.urls', namespace="home")),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^ngtodo/', include('todo.urls', namespace="ngtodo")),
    url(r'^auth/', include('authentication.urls', namespace="authentication")),
    url(r'^timetable/', include('time_table.urls', namespace="time_table")),
    url(r'^api/', include('api.urls', namespace="api")),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rosi_parse/', include('rosi_parse.urls', namespace='rosi')),
)

AbArticulus/todo/urls.py
from django.conf.urls import patterns, url

from todo.views import TodoView, TodoList, TodoDetail


urlpatterns = patterns(
    '',
    url(r'^$', TodoView.as_view(), name='todo_home'),
    url(r'^todos/$', TodoList.as_view(), name="todos_list"),
    url(r'^todos/(?P<pk>[0-9]+)/$', TodoDetail.as_view(), name="todos_update"),
)

AbArticulus/todo/models.py
from django.db import models


class Todo(models.Model):
    item = models.CharField(max_length=255)
    is_done = models.BooleanField(default=False)

AbArticulus/todo/views.py
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework.parsers import JSONParser

from django.views.generic import TemplateView

from todo.models import Todo
from todo.serializers import TodoSerializer


class TodoView(TemplateView):
    template_name = 'todo.html'


class TodoMixin(object):
    queryset = Todo.objects.all().order_by('-id')
    serializer_class = TodoSerializer
    parser_classes = (JSONParser,)


class TodoList(TodoMixin, ListCreateAPIView):
    """Return a list of all the todos, or create new ones."""
    pass


class TodoDetail(TodoMixin, RetrieveUpdateDestroyAPIView):
    """Return a specific todo, update it, or delete it."""
    pass

AbArticulus/todo/templates/todo.html
{% load staticfiles %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static "exampleApp/css/exampleApp.dist.css" %}">
    <script src="{% static "exampleApp/js/exampleApp.dist.js" %}"></script>
{% endblock extra_head %}

{% block main_content %}

<div ng-app="ToDoApp">
    <div ng-view></div>
</div>

{% endblock main_content %}

{% block extra_javascript %}

<script>
    // Bootstrap Django data for angular
    window.jsBootstrap = {};
    window.jsBootstrap.todoListUrl = "{% url "ngtodo:todos_list" %}";
    window.jsBootstrap.todoUpdateUrl = "{% url "ngtodo:todos_update" pk=0 %}";
    window.jsBootstrap.staticUrl = "{% static "" %}";
</script>
{% endblock %}